// <auto-generated />
using EroMangaDB.Tables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EroMangaDB.Migrations
{
    [DbContext(typeof(DataBase_1))]
    [Migration("20221219044300_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31");

            modelBuilder.Entity("EroMangaDB.Entities.FilteredImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<long>("ZipEntryLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FilteredImages");
                });

            modelBuilder.Entity("EroMangaDB.Entities.MangaTagInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbsolutePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("CM_session")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDL")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFullColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LongShort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MagazinePublished")
                        .HasColumnType("TEXT");

                    b.Property<string>("MangaName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NonMosaic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PaisIsDouble")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relative_ACG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translator")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnknownTags")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ManTagInfos");
                });

            modelBuilder.Entity("EroMangaDB.Entities.ReadingInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbsolutePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContentTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MangaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MangaName_Translated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagPieces")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ReadingInfos");
                });

            modelBuilder.Entity("EroMangaDB.Entities.TatCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TagCategorys");
                });
#pragma warning restore 612, 618
        }
    }
}
