// <auto-generated />
using EroMangaDB.Tables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EroMangaDB.Migrations
{
    [DbContext(typeof(DataBase_Version2))]
    [Migration("20230301072116_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31");

            modelBuilder.Entity("EroMangaDB.Entities.FilteredImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<long>("ZipEntryLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FilteredImages");
                });

            modelBuilder.Entity("EroMangaDB.Entities.ReadingInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbsolutePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContentTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MangaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MangaName_Translated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsAddedByUser")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ReadingInfos");
                });

            modelBuilder.Entity("EroMangaDB.Entities.TagCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TagCategorys");
                });
#pragma warning restore 612, 618
        }
    }
}
