<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Configurations>Debug;Release;Debug_TestFolder</Configurations>
    <PackageId>Core</PackageId>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Common" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Config.Net" />
    <PackageReference Include="itext7" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MyLibrary\CommonLibrary\CommonLibrary.csproj" />
    <ProjectReference Include="..\Database\Database.csproj" />
  </ItemGroup>
</Project>
