<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateTemporaryStoreCertificate>False</GenerateTemporaryStoreCertificate>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x86|x64|arm64</AppxBundlePlatforms>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Debug_TestFolder</Configurations>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <DefaultLanguage>zh-CN</DefaultLanguage>
    <PackageCertificateThumbprint>AFCF4DC0CC25ABD02C39FCFD455AA8CD2E03C414</PackageCertificateThumbprint>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Themes\**" />
    <EmbeddedResource Remove="Themes\**" />
    <None Remove="Themes\**" />
    <Page Remove="Themes\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Assets\money100.jpg" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\AppIcons\BadgeLogo.scale-100.png" />
    <None Remove="Assets\AppIcons\BadgeLogo.scale-125.png" />
    <None Remove="Assets\AppIcons\BadgeLogo.scale-150.png" />
    <None Remove="Assets\AppIcons\BadgeLogo.scale-200.png" />
    <None Remove="Assets\AppIcons\BadgeLogo.scale-400.png" />
    <None Remove="Assets\AppIcons\SplashScreen.scale-400.png" />
    <None Remove="Assets\AppIcons\StoreLogo.scale-100.png" />
    <None Remove="Assets\AppIcons\StoreLogo.scale-125.png" />
    <None Remove="Assets\AppIcons\StoreLogo.scale-150.png" />
    <None Remove="Assets\AppIcons\StoreLogo.scale-200.png" />
    <None Remove="Assets\AppIcons\StoreLogo.scale-400.png" />
    <None Remove="Assets\SVGs\book.svg" />
    <None Remove="Assets\SVGs\error.svg" />
    <None Remove="author.txt" />
    <None Remove="ResourceDictionarys\DefaultControlStyle.xaml" />
    <None Remove="ResourceDictionarys\FunctionShowerControl.xaml" />
    <None Remove="ResourceDictionarys\NamedControlStyle.xaml" />
    <None Remove="ResourceDictionarys\TitleContentPairTheme.xaml" />
    <None Remove="ResourceDictionarys\ValueConverters.xaml" />
    <None Remove="UserControls\CoverWithContextFlyout.xaml" />
    <None Remove="UserControls\MangaCoverTags.xaml" />
    <None Remove="UserControls\MangaDetailInfo.xaml" />
    <None Remove="UserControls\MangaOpenButton.xaml" />
    <None Remove="UserControls\MangasGridView.xaml" />
    <None Remove="UserControls\SettingParts\ManageMangaOpenWay3Setting.xaml" />
    <None Remove="UserControls\TagInfo.xaml" />
    <None Remove="UserControls\TagItemsRepeater.xaml" />
    <None Remove="UserControls\TagListOrder.xaml" />
    <None Remove="UserControls\TagListOrder2.xaml" />
    <None Remove="UserControls\TagTextBlock.xaml" />
    <None Remove="Views\ContentDialogPages\RenameCategoryName.xaml" />
    <None Remove="Views\ContentDialogPages\RenameDialog.xaml" />
    <None Remove="Views\MainPage.xaml" />
    <None Remove="Views\MainPageChildPages\Bookcase.xaml" />
    <None Remove="Views\MainPageChildPages\FindSameManga.xaml" />
    <None Remove="Views\MainPageChildPages\IrregularNameSearch.xaml" />
    <None Remove="Views\MainPageChildPages\LibraryPage.xaml" />
    <None Remove="Views\MainPageChildPages\RemoveRepeatTags.xaml" />
    <None Remove="Views\MainPageChildPages\RemoveRepeatTags2.xaml" />
    <None Remove="Views\MainPageChildPages\ServerPage.xaml" />
    <None Remove="Views\MainPageChildPages\SettingPage.xaml" />
    <None Remove="Views\MainPageChildPages\TagsManagePage.xaml" />
    <None Remove="Views\SettingPageChildPages\CommonSettingPage.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Controls.RangeSelector" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.TokenizingTextBox" />
    <PackageReference Include="DJDQfff.BaiduTranslateAPI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="SharpCompress" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <!-- 
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MyLibrary\CommonLibrary\CommonLibrary.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Database\Database.csproj" />
    <ProjectReference Include="..\Server\Server.csproj" />
    <ProjectReference Include="..\UnoLibrary\UnoLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="ResourceDictionarys\DefaultControlStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="ResourceDictionarys\FunctionShowerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="ResourceDictionarys\NamedControlStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="ResourceDictionarys\TitleContentPairTheme.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="ResourceDictionarys\ValueConverters.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UserControls\ManageMangaOpenWay3Setting.xaml">
      <IsDefaultItem>true</IsDefaultItem>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UserControls\MangaBasicInfo\Cover.xaml">
      <IsDefaultItem>true</IsDefaultItem>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UserControls\TagListOrder.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\ContentDialogPages\OverviewInformation.xaml">
      <IsDefaultItem>true</IsDefaultItem>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\Bookcase.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\FindSameManga.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\LibraryPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\RemoveRepeatTags.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\GlobalSearchPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\SettingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\MainPageChildPages\TagsManagePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\SettingPageChildPages\CommonSettingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\ContentDialogPages\RenameDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UserControls\TagInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="UserControls\MangaDetailInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UserControls\BriefInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <!-- 
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_TestFolder|x86'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_TestFolder|x64'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_TestFolder|ARM64'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
    <NoWarn />
  </PropertyGroup>
  <ItemGroup>
    <CustomAdditionalCompileInputs Remove="UserControls\RenameMangaByEditString.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Resource Remove="UserControls\RenameMangaByEditString.xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\TagTextBlock.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\TagItemsRepeater.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\ContentDialogPages\RenameCategoryName.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\CoverWithContextFlyout.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\RenameMangaByDragTag.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\MainPageChildPages\RemoveRepeatTags2.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\MangaOpenButton.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\MainPageChildPages\IrregularNameSearch.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\SettingParts\ManageMangaOpenWay3Setting.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\MangaCoverTags.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\TagListOrder2.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\MainPageChildPages\ServerPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\MangaBasicInfo\Name.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <PRIResource Remove="Themes\**" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="UserControls\MangasGridView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <PRIResource Update="Resources.language-en.resw">
      <IsDefaultItem>true</IsDefaultItem>
    </PRIResource>
  </ItemGroup>
  <ItemGroup>
    <PRIResource Update="Resources.language-zh-CN.resw">
      <IsDefaultItem>true</IsDefaultItem>
    </PRIResource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="UserControls\ManageMangaOpenWay3Setting.xaml.cs">
      <IsDefaultItem>true</IsDefaultItem>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="UserControls\MangaBasicInfo\Cover.xaml.cs">
      <IsDefaultItem>true</IsDefaultItem>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <Compile Update="Views\ContentDialogPages\OverviewInformation.xaml.cs">
      <IsDefaultItem>true</IsDefaultItem>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
