<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <!-- 显式指定为 MSIX 打包模式 -->
    <AppxPackage>true</AppxPackage>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <OutputType>Exe</OutputType>
    <!--<UnoDisableHotDesign>true</UnoDisableHotDesign>-->
    <!--这个顺序有很多奇怪问题，有时候突然就出问题了-->
    <TargetFrameworks>
		  net10.0-desktop;
	      net10.0-android;
	      net10.0-ios;
	      net10.0-windows10.0.26100.0;
	      net10.0-browserwasm;
	      net10.0
  </TargetFrameworks>
    <UnoSingleProject>true</UnoSingleProject>
    <!-- Display name -->
    <ApplicationTitle>本子管理器</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>djdqfff.EroMangaBrowser.Debug</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>djdqfff</ApplicationPublisher>
    <!-- Package Description -->
    <Description>EroMangaBrowser, Local Network Browser For EroMangaManager. Powered by Uno Platform.</Description>
    <!--
      If you encounter this error message:

        error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll.
        Please update to a newer .NET SDK in order to reference this assembly.

      This means that the two packages below must be aligned with the "build" version number of
      the "Microsoft.Windows.SDK.BuildTools" package above, and the "revision" version number
      must be the highest found in https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref.
    -->
    <!-- <WindowsSdkPackageVersion>10.0.22621.28</WindowsSdkPackageVersion> -->
    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>Mvvm;Toolkit;SkiaRenderer;Localization;Hosting  </UnoFeatures>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!--   在dotnet publish命令行中使用-r 参数更好   <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm;android-arm64</RuntimeIdentifiers>
  -->
    <!--直接写无效<RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>-->
  </PropertyGroup>
  <!-- 在文件底部添加这个 Group -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(TargetFramework)' == 'net10.0-android'">
    <ApplicationId>djdqfff.EroMangaBrowser</ApplicationId>
    <EnableLLVM>True</EnableLLVM>
    <PublishTrimmed>True</PublishTrimmed>
    <RunAOTCompilation>False</RunAOTCompilation>
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningAlias>djdqfff</AndroidSigningAlias>
    <AndroidSigningStorePass>512131415zcb</AndroidSigningStorePass>
    <AndroidSigningKeyPass>512131415zcb</AndroidSigningKeyPass>
    <AndroidSigningKeyAlias>djdqfff</AndroidSigningKeyAlias>
    <AndroidSigningKeyStore>..\..\DJDQfff_new.pfx</AndroidSigningKeyStore>
    <!-- Release 配置：关闭快速部署，禁用调试，确保可以存档发布 -->
    <AndroidFastDeploymentType></AndroidFastDeploymentType>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
    <AndroidDebuggable>True</AndroidDebuggable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" />
    <PackageReference Include="DJDQfff.BaiduTranslateAPI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\UnoLibrary\UnoLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <UnoIcon Include="Assets\Icons\icon.svg" />
  </ItemGroup>
</Project>
